on:
  push:
    paths:
      - '**.html'

permissions:
  contents: write

jobs:
  compress-html-files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0
      - name: compress
        run: app/html_to_cpp_array.sh
      - name: commit
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "GitHub Actions"
          git commit -am "chore: generate html files buffer"
          git push